
spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false  #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/admin_class?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 987654
          driver-class-name: com.mysql.cj.jdbc.Driver
        

 